#-*- coding: utf-8 -*-
# it modifies DB one by one by hand
# refer: http://kanae.2ch.net/test/read.cgi/otoge/1424491448/
# thx to XERT*

def parse12():
	data = [
		(u"Leggendaria", [
			(u"Ancient Scapes†LEGGENDARIA", "SPA"), 
			(u"Close the World feat.a☆ru†LEGGENDARIA", "SPA"), 
			(u"Feel The Beat†LEGGENDARIA", "SPA"), 
			(u"invoker†LEGGENDARIA", "SPA"), 
			(u"Sigmund†LEGGENDARIA", "SPA"),
			(u"Verflucht†LEGGENDARIA", "SPA"),
			(u"疾風迅雷†LEGGENDARIA", "SPA")]),
		(u"처리력 S+", [
			(u"3y3s", "SPA"), 
			(u"Go Beyond!!", "SPA"), 
			(u"卑弥呼", "SPA"), 
			(u"冥", "SPA")]),
		(u"개인차 S+", [
			(u"DIAVOLO", "SPA"), 
			(u"Plan 8", "SPA"), 
			(u"Thor\'s Hammer", "SPA"), 
			(u"Timepiece phase II (CN ver.)", "SPA"), 
			(u"灼熱Beach Side Bunny", "SPA")]),
		(u"처리력 S", [
			(u"Confiserie", "SPA"), 
			(u"Chrono Diver -Pendulum-", "SPA"), 
			(u"Elemental Creation", "SPA"), 
			(u"IX", "SPA"), 
			(u"perditus†paradisus", "SPA"), 
			(u"共鳴遊戯の華", "SPA"), 
			(u"煉獄のエルフェリア", "SPA")]),
		(u"개인차 S", [
			(u"Almagest", "SPA"), 
			(u"BLACK. by X-Cross Fade", "SPA"), 
			(u"Fascination MAXX", "SPA")]),
		(u"처리력 A+", [
			(u"Sigmund", "SPA"), 
			(u"Verflucht", "SPA"), 
			(u"嘆きの樹", "SPA")]),
		(u"개인차 A+", [
			(u"Snake Stick", "SPA"), 
			(u"VOX UP", "SPA")]),
		(u"처리력 A", [
			(u"Bad Maniacs", "SPA"), 
			(u"Despair of ELFERIA", "SPA"), 
			(u"Flashes", "SPA"), 
			(u"HAERETICUS", "SPA"), 
			(u"KAISER PHOENIX", "SPA"), 
			(u"MENDES", "SPA"), 
			(u"PARADISE LOST", "SPA"), 
			(u"quell ~ the seventh slave ~", "SPA"), 
			(u"reunion", "SPA"), 
			(u"Zirkfied", "SPA"), 
			(u"キャトられ♥恋はモ～モク", "SPA"), 
			(u"ピアノ協奏曲第１番”蠍火”", "SPA"), 
			(u"天空の夜明け", "SPA")]),
		(u"개인차 A", [
			(u"BLUE MIRAGE", "SPA"), 
			(u"fallen leaves -IIDX Edit.-", "SPA"), 
			(u"Hollywood Galaxy", "SPA"), 
			(u"JOMANDA", "SPA"), 
			(u"PARANOiA ~HADES~", "SPA"), 
			(u"rage against usual", "SPA"), 
			(u"Red. by Full Metal Jacket", "SPA"), 
			(u"Watch Out Pt.2", "SPA"), 
			(u"音樂", "SPA")]),
		(u"처리력 B+", [
			(u"EXUSIA", "SPA"), 
			(u"G59", "SPA"), 
			(u"INSOMNIA", "SPA"), 
			(u"Monopole.", "SPA"), 
			(u"STULTI", "SPA"), 
			(u"Timepiece phase II", "SPA"), 
			(u"TOXIC VIBRATION", "SPA"), 
			(u"We're so Happy (p*light)", "SPA"), 
			(u"YAKSHA", "SPA"), 
			(u"子供の落書き帳", "SPA"), 
			(u"轟け！恋のビーンボール！！", "SPA"), 
			(u"†渚の小悪魔ラヴリィ～レイディオ†(IIDX EDIT)", "SPA")]),
		(u"개인차 B+", [
			(u"BLUE DRAGON", "SPA"), 
			(u"DAY DREAM", "SPA"), 
			(u"Rave*it!! Rave*it!!", "SPA"), 
			(u"ra'am", "SPA"), 
			(u"Valanga", "SPA")]),
		(u"처리력 B", [
			(u"BITTER CHOCOLATE STRIKE", "SPA"), 
			(u"Closes the World feat a☆ru", "SPA"), 
			(u"Colorful Cookie", "SPA"), 
			(u"Dances with Snow Fairies", "SPA"), 
			(u"DARK LEGACY", "SPA"), 
			(u"Devilz Staircase", "SPA"), 
			(u"DOMINION", "SPA"), 
			(u"Hollywood Galaxy (DJ NAGAI Remix)", "SPA"), 
			(u"Immortal", "SPA"), 
			(u"Ludus In Tenebris", "SPA"), 
			(u"NEO GENERATOR SEVEN", "SPA"), 
			(u"neu", "SPA"), 
			(u"Proof of the existence", "SPA"), 
			(u"quaver♪", "SPA"), 
			(u"Session 9 -Chronicles-", "SPA"), 
			(u"Shooting Fireball", "SPA"), 
			(u"SYNC-ANTHEM", "SPA"), 
			(u"The Limbo", "SPA"), 
			(u"疾風迅雷", "SPA"), 
			(u"聖人の塔", "SPA"), 
			(u"たまゆら", "SPA"), 
			(u"不沈艦CANDY", "SPA")]),
		(u"개인차 B", [
			(u"FANTASTIC THREE", "SPA"), 
			(u"IMPLANTATION", "SPA"), 
			(u"Sense 2007", "SPA"), 
			(u"アストライアの双皿", "SPA"), 
			(u"リリーゼと炎龍レーヴァテイン", "SPA")]),
		(u"처리력 C", [
			(u"Ancient Scapes", "SPA"), 
			(u"Broken Sword", "SPA"), 
			(u"Candy Galy", "SPA"), 
			(u"Colors (radio edit)", "SPA"), 
			(u"ELECTRIC MASSIVE DIVER", "SPA"), 
			(u"entelecheia", "SPA"), 
			(u"Evans", "SPA"), 
			(u"Feel The Beat", "SPA"), 
			(u"fffff", "SPA"), 
			(u"GAIA", "SPA"), 
			(u"GOLDEN CROSS", "SPA"), 
			(u"Idola", "SPA"), 
			(u"Last Dance", "SPA"), 
			(u"NNRT", "SPA"), 
			(u"One More Lovely", "SPA"), 
			(u"PUNISHER", "SPA"), 
			(u"Sol Cosine Job 2", "SPA"), 
			(u"即席！脳直★ミュージックシステム", "SPA"), 
			(u"トリカゴノ鳳凰", "SPA"), 
			(u"海神", "SPA"), 
			(u"表裏一体！？怪盗いいんちょの悩み♥", "SPA")]),
		(u"개인차 C", [
			(u"Adularia", "SPA"), 
			(u"FAKE TIME", "SPA"), 
			(u"Scripted Connection⇒ A mix", "SPA"), 
			(u"ZZ", "SPA"), 
			(u"ワルツ第17番 ト短調”大犬のワルツ”", "SPA")]),
		(u"처리력 D", [
			(u"AA", "SPA"), 
			(u"ALBIDA", "SPA"), 
			(u"Broken", "SPA"), 
			(u"Concertino in Blue", "SPA"), 
			(u"FIRE FIRE", "SPA"), 
			(u"Liberation", "SPA"), 
			(u"oratio", "SPA"), 
			(u"SOLID STATE SQUAD", "SPA"), 
			(u"SpaceLand☆TOYBOX", "SPA"), 
			(u"The Sampling Paradise", "SPA"), 
			(u"Thunderbolt", "SPA"), 
			(u"Todestrieb", "SPA"), 
			(u"True Blue", "SPA"), 
			(u"VENESSA", "SPA"), 
			(u"少年A", "SPA"), 
			(u"電人、暁に斃れる。", "SPA")]),
		(u"개인차 D", [
			(u"eRAseRmOToRpHAntOM", "SPA"), 
			(u"ICARUS", "SPA"), 
			(u"Innocent Walls", "SPA"), 
			(u"one or eight", "SPA"), 
			(u"PLEASES DON\'T GO", "SPA"), 
			(u"桜", "SPA")]),
		(u"처리력 E", [
			(u"ΕΛΠΙΣ", "SPA"), 
			(u"F", "SPA"), 
			(u"Invoker", "SPA"), 
			(u"LASER CRUSTER", "SPA"), 
			(u"Little Star", "SPA"), 
			(u"moon_child", "SPA"), 
			(u"mosaic", "SPA"), 
			(u"Symmetry", "SPA"), 
			(u"TIEFSEE", "SPA"), 
			(u"V", "SPA"), 
			(u"カゴノトリ～弐式～", "SPA"), 
			(u"黒髪乱れし修羅となりて", "SPA"), 
			(u"紅牡丹", "SPA")]),
		(u"개인차 E", [
			(u"Innocent Walls", "SPH"), 
			(u"sakura storm", "SPA"), 
			(u"SCREAM SQUAD", "SPA"), 
			(u"TROOPERS", "SPA"), 
			(u"雪月花", "SPA")]),
		(u"처리력 F", [
			(u"A", "SPA"), 
			(u"gigadelic", "SPA"), 
			(u"gigadelic", "SPH"), 
			(u"Ristaccia", "SPA"), 
			(u"SPECIAL SUMMER CAMPAIGN", "SPA"), 
			(u"tripping contact", "SPA")])]
	return data