# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-07 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iidxrank', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
                ('writer', models.CharField(max_length=100)),
                ('tag', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('attr', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='boardcomment',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iidxrank.BoardComment'),
        ),
    ]
