# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-08 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iidxrank', '0002_auto_20160707_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardcomment',
            name='tag',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boardcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='iidxrank.BoardComment'),
        ),
    ]
