# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-08 15:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iidxrank', '0003_auto_20160709_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardcomment',
            name='tag',
            field=models.CharField(default=b'', max_length=100),
        ),
        migrations.AlterField(
            model_name='boardpost',
            name='tag',
            field=models.CharField(default=b'', max_length=100),
        ),
    ]
