# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-08 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iidxrank', '0004_auto_20160709_0051'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoardPost',
        ),
    ]
