# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-08 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('iidxrank', '0005_delete_boardpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoardPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=1000)),
                ('writer', models.CharField(max_length=100)),
                ('tag', models.CharField(default=b'', max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('attr', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
