# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-08 16:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iidxrank', '0006_boardpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpost',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iidxrank.Board'),
        ),
    ]
