# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-08 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iidxrank', '0007_boardpost_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardpost',
            name='permission',
            field=models.IntegerField(default=0),
        ),
    ]
