# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-09 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iidxrank', '0008_boardpost_permission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardcomment',
            name='board',
        ),
        migrations.AddField(
            model_name='boardcomment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iidxrank.BoardPost'),
        ),
    ]
