# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-13 13:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iidxrank', '0009_auto_20160709_1706'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BannedUser',
        ),
        migrations.DeleteModel(
            name='BannedWord',
        ),
        migrations.RemoveField(
            model_name='boardcomment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='boardcomment',
            name='post',
        ),
        migrations.RemoveField(
            model_name='boardpost',
            name='board',
        ),
        migrations.RemoveField(
            model_name='songcomment',
            name='ranktable',
        ),
        migrations.RemoveField(
            model_name='songcomment',
            name='song',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='BoardComment',
        ),
        migrations.DeleteModel(
            name='BoardPost',
        ),
        migrations.DeleteModel(
            name='SongComment',
        ),
    ]
