# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-14 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iidxrank', '0012_player_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='original',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='iidxrank.Song'),
        ),
    ]
