# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-15 05:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('iidxrank', '0011_song_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerCalc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('valid', models.IntegerField(default=0)),
                ('sp_l', models.FloatField(default=0)),
                ('sp_w', models.FloatField(default=0)),
                ('dp_l', models.FloatField(default=0)),
                ('dp_w', models.FloatField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iidxrank.Player')),
            ],
        ),
        migrations.CreateModel(
            name='SongCalc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=20)),
                ('ez_l', models.FloatField(default=0)),
                ('ez_w', models.FloatField(default=0)),
                ('nm_l', models.FloatField(default=0)),
                ('nm_w', models.FloatField(default=0)),
                ('hd_l', models.FloatField(default=0)),
                ('hd_w', models.FloatField(default=0)),
                ('ex_l', models.FloatField(default=0)),
                ('ex_w', models.FloatField(default=0)),
                ('fc_l', models.FloatField(default=0)),
                ('fc_w', models.FloatField(default=0)),
                ('score_avg', models.FloatField(default=0)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iidxrank.Player')),
            ],
        ),
    ]
