# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-15 06:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playercalc',
            name='player',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='iidxrank.Player'),
        ),
        migrations.AlterField(
            model_name='songcalc',
            name='song',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='iidxrank.Player'),
        ),
    ]
