# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-15 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('update', '0002_auto_20160715_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='songcalc',
            name='valid',
            field=models.IntegerField(default=0),
        ),
    ]
