# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-04-13 07:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='board.BoardComment'),
        ),
        migrations.AlterField(
            model_name='boardcomment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='board.BoardPost'),
        ),
        migrations.AlterField(
            model_name='boardcomment',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='boardpost',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='board.Board'),
        ),
        migrations.AlterField(
            model_name='boardpost',
            name='tag',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
