# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-13 03:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20170413_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardpost',
            name='writer',
            field=models.TextField(),
        ),
    ]
